---
baseURL: https://duffy.xyz/
languageCode: en-us
title: James Duffy
theme: simple

enableGitInfo: true

author:
    name: James Duffy
    twitter: duffy0
    instagram: duffy0
    flickr: dffy
    email: james@duffy.xyz
    github: jamesduffy
    keybase: dffy

taxonomy:
  tag: tags

bloggroupby: "year"

permalinks:
  posts: /:year/:slug/

menu:
  main:
  - identifier: about
    name: About
    url: /about/
    weight: -200
  - identifier: archive
    name: Archive
    url: /archive/
    weight: -100
  - identifier: photography
    name: Photography
    url: /photography/
    weight: -90
