---
baseURL: https://duffy.xyz/
languageCode: en-us
title: James Duffy
theme: simple

author:
    name: James Duffy
    twitter: duffy0
    instagram: duffy0
    flickr: dffy
    email: james@duffy.xyz
    github: jamesduffy
    keybase: dffy

bloggroupby: "year"

permalinks:
  posts: /:year/:slug/

menu:
  main:
  - identifier: about
    name: About
    url: /
    weight: -200
  - identifier: radio
    name: Ham Radio
    url: /radio/
    weight: -100
  - identifier: posts
    name: Posts
    url: /posts/
    weight: -90
  - identifier: photography
    name: Photography
    url: /photography/
    weight: -80
  - identifier: use
    name: Things I Use
    url: /uses/
    weight: -80
