---
baseURL: https://duffy.xyz/
languageCode: en-us
title: James Duffy
theme: duffy2021

enableGitInfo: true

params:
  title: James Duffy
  description: Hi! 👋 I'm James Duffy. I'm an infrastructure engineer, cyclist, and photographer.
  images:
  - /img/content/about/self-3-small.png

author:
  name: James Duffy
  description: I'm Duffy, a Devops Engineer writing code for fun and profit.
  twitter: duffy0
  instagram: duffy0
  flickr: dffy
  email: james@duffy.xyz
  github: jamesduffy
  keybase: dffy

taxonomies:
  tag: tags

bloggroupby: "year"

relativeURLs: true

permalinks:
  posts: /:year/:slug/

menu:
  main:
  - identifier: about
    name: About
    url: /about/
    weight: -200
  - identifier: blog
    name: Blog
    url: /archive/
    weight: -100
  - identifier: photography
    name: Photography
    url: /photography/
    weight: -90

  footer:
  - identifier: about
    name: About
    url: /about/
    weight: -200
  - identifier: blog
    name: Blog
    url: /archive/
    weight: -100
  - identifier: photography
    name: Photography
    url: /photography/
    weight: -90
  - identifier: notes
    name: Notes
    url: /notes/
    weight: -90
  - identifier: changelog
    name: Changelog
    url: /changelog/
    weight: -90

markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 1

  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: dracula
    tabWidth: 4
